services:
  app:
    build: 
      context: .  # Сборка из корня проекта
      dockerfile: Dockerfile  # Используем Dockerfile из корня
    ports:
      - "8501:8501"  # Пробрасываем порт: 8000 с хоста → 8501 в контейнере
    volumes:
      - ./app_src:/app/app_src  # Монтируем папку с кодом для hot-reload
    working_dir: /app/app_src  # Рабочая директория в контейнере
    command: > 
      sh -c "poetry run streamlit run app.py --server.port=8501"
    # Команда запуска:
    # 1. Используем Poetry для управления зависимостями
    # 2. Запускаем Streamlit на порту 8501